### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by yebai** [nsiccha/StanBlocks.jl#2]
Hi, @nsiccha, `README` contains the following example

```julia
julia_implementation(::Val{:earn_height}; N, earn, height, kwargs...) = begin 
    @stan begin 
        @parameters begin
            beta::vector[2]
            sigma::real(lower=0.)
        end
        @model begin
            earn ~ normal(@broadcasted(beta[1] + beta[2] * height), sigma);
        end
    end
end
```

Is there a reason for `@broadcasted` instead of more Julian broadcasting syntax

```julia
   earn ~ normal((beta[1] + beta[2] .* height), sigma); 
```

**Comment by nsiccha** [comment]
@broadcasted replaces Base's @., but doesn't materialize the result, ie doesn't allocate. Instead, the broadcasted expression gets fed into the lpdf function (compare https://github.com/nsiccha/StanBlocks.jl/blob/cf7cc37a6f22d1356d44c2b28081cfe3cd6fcdf7/src/functions.jl#L86), where it then gets fed into another (allocation free) @broadcasted, which then finally gets reduced in a (again allocation free) way that tries to be clever about not doing potentially expensive computation repeatedly (compare the functions in the block starting here: https://github.com/nsiccha/StanBlocks.jl/blob/cf7cc37a6f22d1356d44c2b28081cfe3cd6fcdf7/src/functions.jl#L11).

I think initial Benchmarking revealed that to be faster than doing it the "standard" way. I think that Stan either already does such an optimization OR is conceivably able to do it via Eigen (C++) expressions, ie without the "user" having to do additional stuff like adding the @broadcasted macro.

Doing it this way, including implementing the lpdf functions myself instead of relying on distributions.jl, made some optimizations easier to do.
